### TODO 24 y 25
### Registro
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
  "nombre": "Javier",
  "tel": "123456789",
  "email": "javier4@gmail.com",
  "password": "Password123"
}



### Login
POST http://127.0.0.1:8000/api/users/login/
Content-Type: application/json

{
  "email": "javier4@gmail.com",
  "password": "Password123"
}



### Perfil
GET http://127.0.0.1:8000/api/users/me/
Cookie: session=a1f298dab2773a3b8e83b15958b368817d6beac5



### Actualización perfil
PUT http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Cookie: session=f052e4dbbd777b20c52b55f828cfaad46fa80588

{
  "nombre": "Javier",
  "tel": "1234567890123",
  "email": "javier4@gmail.com",
  "password": "Password123"
}

### Actualización perfil
PATCH http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Cookie: session=f052e4dbbd777b20c52b55f828cfaad46fa80588


{
  "nombre": "Javier2"
}




### Logout
DELETE http://127.0.0.1:8000/api/users/logout/
Cookie: session=f052e4dbbd777b20c52b55f828cfaad46fa80588



### Baja
DELETE http://127.0.0.1:8000/api/users/me/
Cookie: session=f052e4dbbd777b20c52b55f828cfaad46fa80588


