# Generated by Django 4.2.11 on 2024-05-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="nombre",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
