# Generated by Django 5.0.4 on 2024-04-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(to="users.actor"),
        ),
    ]
