# Generated by Django 5.0.4 on 2024-04-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_actor_remove_movie_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
